// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import notify from 'devextreme/ui/notify';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    toastColor: string;
    onValueChanged(e: { value: string; }) {
        this.toastColor = e.value;
        if (this.toastColor) {
            notify({
                message: 'The color has been changed',
                onShowing: (e: { component: { content: () => { (): any; new(): any; style: { (): any; new(): any; backgroundColor: string; }; }; }; }) => {
                    e.component.content().style.backgroundColor = this.toastColor;
                }
            });
        }
    }
}


<dx-color-box
    label="Pick a color"
    value="#000000"
    [editAlphaChannel]="true"
    applyButtonText="Show notification"
    [showClearButton]="true"
    (onValueChanged)="onValueChanged($event)"
>
</dx-color-box>

// React/src/App.tsx
import { useCallback } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import { ColorBox } from 'devextreme-react/color-box';
import type { ColorBoxTypes } from 'devextreme-react/color-box';
import notify from 'devextreme/ui/notify';
import type { ToastTypes } from 'devextreme-react/toast';

function App(): JSX.Element {
  const onValueChanged = useCallback((e: ColorBoxTypes.ValueChangedEvent) => {
    const toastColor = e.value;
    if (toastColor) {
      notify({
        message: 'The color has been changed',
        onShowing: (args: ToastTypes.ShowingEvent) => {
          args.component.content().style.backgroundColor = toastColor;
        },
      });
    }
  }, []);

  return (
    <div id="container">
      <ColorBox
        label="Pick a color"
        defaultValue="#000000"
        editAlphaChannel={true}
        applyButtonText="Show notification"
        showClearButton={true}
        onValueChanged={onValueChanged}
      />
    </div>
  );
}

export default App;
